#!/bin/fish
if playerctl -l >/dev/null = "No players were found";
  echo "badgers"
else if playerctl status >/dev/null = "Playing" ;
  title=`exec playerctl metadata xesam:title`
  artist=`exec playerctl metadata xesam:artist`
  #album=`exec playerctl metadata xesam:album`
  length=`exec playerctl metadata mpris:length`
  songlength=`exec python ~/.config/polybar/songlength.py $length`
  echo " $title - $artist - ($songlength)"
else if playerctl status >/dev/null = "Paused" ;
   title=`exec playerctl metadata xesam:title`
   artist=`exec playerctl metadata xesam:artist`
   #album=`exec playerctl metadata xesam:album`
   length=`exec playerctl metadata mpris:length`
   songlength=`exec python ~/.config/polybar/songlength.py $length`
   echo " $title - $artist - ($songlength)"
end
